// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoiYNOXQW_6sjW4B6aoQxwhLjuQGmGu18',
    appId: '1:905268420062:web:86fe46e0cee4e11f9f914f',
    messagingSenderId: '905268420062',
    projectId: 'chatscreen-a193d',
    authDomain: 'chatscreen-a193d.firebaseapp.com',
    storageBucket: 'chatscreen-a193d.appspot.com',
    measurementId: 'G-MRBEKDSER3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkdWzbng2nOKHvCnUqBPx_sbwB_cJcWE',
    appId: '1:905268420062:android:7701de12094accc09f914f',
    messagingSenderId: '905268420062',
    projectId: 'chatscreen-a193d',
    storageBucket: 'chatscreen-a193d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPMN00qYluBQIop6B-XhtYCINS5Hy1NEI',
    appId: '1:905268420062:ios:7b1a0040eaf4e1629f914f',
    messagingSenderId: '905268420062',
    projectId: 'chatscreen-a193d',
    storageBucket: 'chatscreen-a193d.appspot.com',
    iosBundleId: 'com.chat.chatscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPMN00qYluBQIop6B-XhtYCINS5Hy1NEI',
    appId: '1:905268420062:ios:d9a0742f7b7baebd9f914f',
    messagingSenderId: '905268420062',
    projectId: 'chatscreen-a193d',
    storageBucket: 'chatscreen-a193d.appspot.com',
    iosBundleId: 'com.chat.chatscreen.RunnerTests',
  );
}
